/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin processor.

  ==============================================================================
*/

#ifndef PLUGINPROCESSOR_H_INCLUDED
#define PLUGINPROCESSOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "../ThirdParty/Pd/cpp/PdBase.hpp"
#include "../ThirdParty/Cream/c.library.hpp"
#include "CicmPatch.h"

#include <set>

using namespace std;

class CamomileAudioProcessor  : public AudioProcessor
{
public:
    class Listener;
private:
    ScopedPointer<pd::PdBase> m_pd;
    CicmPatch                 m_patch;
    float*                    m_buffer_in;
    float*                    m_buffer_out;
    
    set<Listener*>            m_listeners;
    mutable mutex             m_mutex;
    
public:
    CamomileAudioProcessor();
    ~CamomileAudioProcessor();

    void prepareToPlay(double sampleRate, int samplesPerBlock) override;
    void releaseResources() override;

    void processBlock(AudioSampleBuffer&, MidiBuffer&) override;

    AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override;

    const String getName() const override;

    int getNumParameters() override;
    float getParameter (int index) override;
    void setParameter (int index, float newValue) override;

    const String getParameterName (int index) override;
    const String getParameterText (int index) override;

    const String getInputChannelName (int channelIndex) const override;
    const String getOutputChannelName (int channelIndex) const override;
    bool isInputChannelStereoPair (int index) const override;
    bool isOutputChannelStereoPair (int index) const override;

    bool acceptsMidi() const override;
    bool producesMidi() const override;
    bool silenceInProducesSilenceOut() const override;
    double getTailLengthSeconds() const override;

    int getNumPrograms() override;
    int getCurrentProgram() override;
    void setCurrentProgram (int index) override;
    const String getProgramName (int index) override;
    void changeProgramName (int index, const String& newName) override;

    void getStateInformation (MemoryBlock& destData) override;
    void setStateInformation (const void* data, int sizeInBytes) override;
    
    inline bool hasPatch() const noexcept {return m_patch.isValid();}
    void loadPatch(const juce::File& file);
    inline CicmPatch const& getPatch() const noexcept {return m_patch;}
    inline bool shouldProcess() const noexcept {return m_pd && m_buffer_in && m_buffer_out;}
    
    // ================================================================================ //
    //                                      LISTENER                                    //
    // ================================================================================ //
    
    void addListener(Listener* listener)
    {
        if(listener)
        {
            lock_guard<mutex> guard(m_mutex);
            m_listeners.insert(listener);
        }
    }
    
    void removeListener(Listener* listener)
    {
        if(listener)
        {
            lock_guard<mutex> guard(m_mutex);
            m_listeners.erase(listener);
        }
    }
    
    vector<Listener*> getListeners() const noexcept
    {
        lock_guard<mutex> guard(m_mutex);
        return vector<Listener*>(m_listeners.begin(), m_listeners.end());
    }
    
    class Listener
    {
    public:
        inline Listener() {}
        
        inline virtual ~Listener() {}
        
        virtual void patchChanged() = 0;
    };

private:
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (CamomileAudioProcessor)
};


#endif  // PLUGINPROCESSOR_H_INCLUDED
